app1/urls.py
from django.urls import path

from . import views

# 'app1' => 아래 name='index'의 별칭
app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    # --- 상세보기 페이지 추가 21.07.12(king) detail, answer url 부여--------------------
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # --- 21.07.13 질문등록 url 부여 --------------------------------------------------
    path('question/create', views.question_create, name='question_create'),
    # --- 21.07.21. 퀴즈 : question_modify url 등록. 위에서 형식 참조. 규칙성 있게 만들면 추후 사용 편리성 증대 -------
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# 질문과 답변 테이블 생성 (21.7.8 김관동)
# 질문 테이블 : Question
# 질문 제목 : subject
# 질문 내용 : content
# 질문작성일자 : create_date
# 답변 테이블 : Answer

# <-------------------- 질문 테이블 --------------->
class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()

# --------------- 21.07.21 컬럼 추가(작성자/글쓴이 author) -----------
#     추가하는 author = 사용자 ID 로 쓸것임.
# on_delete=models.CASCADE : User 에 있는 값이 삭제되면 해당 값과 연결된
#                            Question 테이블의 데이터를 삭제 하라는 의미
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # modify_date 컬럼 = 수정일자(작성한 질문에 대한)
    # null=True : 해당 컬럼에 Null 값 허용
    # blank=True : 폼 데이터 검사시 값이 없어도 된다는 의미.
    modify_date = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return self.subject


# ---------------------- 답변 테이블 -------------->
# 답변 테이블 : Answer
# 답변 내용 : answer_content
# 답변 작성일자 : create_date
# 질문 제목 : question(어떤 질문에 대한 답변인지 알아야하기 때문에)
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_content = models.TextField()
    create_date = models.DateTimeField()
    # null=True : 컬럼에 null 값 허용.
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    modify_date = models.DateTimeField(null=True, blank=True)

app1/forms.py
from django import forms
from app1.models import Question

# QuestionForm 같은 클래스 장고 폼이라 부른다
# 장고폼에는 2가지가 있다
# 일반 폼, 모델 폼 2가지.
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

# ----- 21.07.14 질문 등록하기 제목, 내용에 부트스트랩적용
#  왜 html 에서 적용하지않고 모듈에서 적용하는가?
#  이유 : 템플릿 태그 {{ form.as_p }} 때문
#  {{ form.as_p }} : 모델 (테이블)의 정보를 받아 form 과 요소를 자동으로 생성하는 템플릿 태그
#  테이블 컬럼 숫자에 관계없이 컬럼을 불러올 수 있다는 장점이 있지만
#  html(template) 단에서 스타일을 적용하디 힘들다 라는 단점이 있음
#  이러한 단점을 widgets 속성을 이용해서 해당 템플릿(html) 로딩시
#  클래스 정보를 전달해주는 방식으로 커버한다
#  key 값은 해당 컬럼명으로 value 값은 적용할 속성으로 쓴다
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

        labels = {
            'subject': '제목',
            'content': '내용',
        }

app1/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
# views.py 의 위치에서 models.py 를 찾아서 question 을 import 하라는 의미.
from .models import Question
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
# 아래 코드에서 app1 은 있어도 없어도 결과는 같다.
from app1.forms import QuestionForm
# 21.07.19. 페이징 처리 관련 모듈 import
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


def index(request):
    # REQUEST 는 외부 사용자의 요청을 받아오는것
    # render : 템플릿에 로딩할때 사용.
    # redirect : url 로 이동시 사용.
    # 사용자가 localhost:8000/app1 페이지 접속 이라는 요청을 보냈다.
    # view -> urls 에 어떤 함수를 실행 할지를 확인.
    # view 에서 model 단에 요청
    # 요청의 내용 : 조회 (question 테이블/모델 create_date 컬럼을 기준으로
    # 정렬해서 가져옴) -> 그 결과를 question_list 변수에 저장
    # 21.07.09 질문 목록 가져오기.('-' 는 내림차순 정리).

    page = request.GET.get('page', '1')

    question_list = Question.objects.order_by('-create_date')
    # context 라는 변수에 딕셔너리 형태로 question_list key 와 value 를 저장
    # 테플릿단에서 해당 데이터를 쉽게 조회하기 위해.

    # 페이징 처리내용 = 가져온 데이터를 10개씩 보여줘라
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    # 아래 코드에서 question_list <-- page_obj 로 변경하면 게시판 한 페이지에 질무글이 10개씩만 보이게 됨.
    # context = {'question_list': question_list}
    context = {'question_list': page_obj}

    # 받은 요청에 대해 (request)
    return render(request, 'app1/question_list.html', context)

def detail(request, question_id):
    # get_object_or_404 : 기본키에 해당하는 건이 없다면 404 출력.
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'app1/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(answer_content=request.POST.get('answer_content'), create_date=timezone.now())
    # redirect : 함수에 전달된 값을 참고해 페이지 이동을 수행하는 함수
    return redirect('app1:detail', question_id=question.id)

# 질문 등록 함수 21.07.13
# @login_required 를 추가해서 만약 질문등록하기 페이지 이동시 로그인이 안되어 있다면
# 로그인 페이지로 먼저 이동 시킨다.
@login_required(login_url='common:login')
def question_create(request):
    # 수정내용 : GET, POST(주소에 데이터가 포함/느리다) 방식에 대한 처리
    # question_form 으로 들어올때
    # 질문을 등록할때
    # post 방식인지 get 방식인지 확인
    # 이유 : 단순히 질문등록 페이지를 오픈한 것인지
    # 아니면 질문등록 페이지에 데이터를 입력해서 저장 한 것인지를 구분
    if request.method == "POST":
        # forms.py 에 설정한 QuestionForm 클래스를 호출
        # request.POST : 사용자가 입력한 데이터를 받아온다.
        form = QuestionForm(request.POST)
        # 변수 form 에 들어온 값이 올바른 값(정상적인 값인지 확인)
        if form.is_valid():
            # 저장을 하기전 잠시 유보.
            # question 변수에 form 에서 받아온 데이터는 넣어 뒸지만
            # 아직 DB 로 저장하지는 않았다
            question = form.save(commit=False)
            # create_date 컬럼을 따로 입력받지않은 이유?
            # 현재시간으로 입력받기 위해
            # view 에서 처리
            question.create_date = timezone.now()
            question.author = request.user
            # .save 없으면 저장 안되서 에러 발생
            question.save()
            return redirect('app1:index')
            # return render('app1:index') <-- 에러
    else:
        form = QuestionForm()
        context = {'form': form}
    return render(request, 'app1/question_form.html', context)

# 21.07.21. King question_modify 관련 추가
def question_modify(request, question_id):
    form = QuestionForm()
    return render(request, 'app1/question_form.html', {'form:form'})



# 21.07.14. 수정 (기존내용 백업)
# def question_create(request):
#     form = QuestionForm()
#     return render(request, 'app1/question_form.html', {'form': form})




# get 방식과 post 방식(데이터 전송방식)
# get 방식  : URL 에 파라미터를 붙여서 전송하는 방식
#             속도가 빠르다는 장점이 있지만
#             URL 에 데이터를 실어서 보내기 때문에 보안에 취약하거나
#             그외 데이터 전송에 여러가지 제한 사항이 있다.
# post 방식 : HTML 의 BODY 영역에 데이터를 실어 보내는 방식 (form)
#             대용량의 데이터를 보낼수있고 주소에 실어 보내지 않기 때문에
#             get 방식에 비해 보안성 또한 좋다
# csrf_token : 브라우저에서 작성된 데이터가 올바른 데이터인지,
#              혹은 진짜 웹 브라우저에서 작성된 데이터인지 판단하는 기능
#             -디장고의 기본기능


# <!--템플릿 태그-->
# <!--{% if 요청 받은 값(question_list)%} : Question_list 가 있을 경우.-->
# <!--{% for 임시변수 in 요청 받은 값(딕셔너리의 키 값) %} : 딕셔너리 키의 value 를 -->
# <!--    반복하여 순차적으로 임시변수에 대입/-->
# <!--{{ 임시변수.컬럼 }} : for 문에 의해 선언 된 임시변수의 컬럼출력(데이터 표현은 중괄호 2개 임. %% 아님.-->
# {{ }} : 데이터와 관련된 내용을 출력할때 사용하는 템플릿 태그
# {% %} : 템플릿 태그의 속성, 문법 등을 사용할때 쓰는 태그

templates/app1/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text style="white-space: pre-line">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    <div class="m-2">{{ question.author.username }}</div>
                    {{ question.create_date }}
                </div>
            </div>
<!--        21.07.21 수정버튼 등록 King -->
            <div class="my-3">
                <a href="{% url 'app1:question_modify' question.id %}" class="btn btm-sm btn-outline-secondary"></a>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3" >
        <div class="card-text" style="white-space: pre-line">
            {{ answer.answer_content }}
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2">
                <div class="m-2">{{ answer.author.username }}</div>
                {{ answer.create_date }}
            </div>
        </div>
    </div> <!--card my-3 end-->
    {% endfor %}

<form action="{% url 'app1:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="answer_content" id="answer_content" rows="15"></textarea>
    <input type="submit" value="답변 등록하기">
</form>
</div>
{% endblock %}

templates/app1/question_detail_backup0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
<link rel ="stylesheet" type="text/css" href="{% static 'style.css' %}">
<h1>{{ question.subject }}</h1>
<p>{{ question.content }}</p>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>{{ answer.answer_content }}</li>
        {% endfor %}
    </ul>
</div>

<form action="{% url 'app1:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="answer_content" id="answer_content" rows="15"></textarea>
    <input type="submit" value="답변 등록하기">
</form>

</body>
</html>

templates/app1/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border=bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
         {% if form.errors %}
          <div class="alert alert-danger" role="alert">
              {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}
                </strong>
                {{ field.errors }}
                {% endif %}
              {% endfor %}
          </div>
        {% endif %}
<!--오류 표시 -->

        <div class="form-group">
<!--label 태그 : input 태그와 연계해서 사용되는 태그
                    input 태스를 제어해서 상태를 변경하게 도와주는 태그
              for : 다른 태그와 결합할때 사용하는 속성.
              결합하고자 하는 태그의 id 값과 같아야함. id 지정한다-->
            <label for="subject">제목</label>
<!--form.컬럼명.value : 오류, 혹은 잘못된 연결 등 예기치 못한 상황이나
                            사용자의 입력 실수가 있었을때 해강 요소에 값이 있었다면
                            그 값의 초기화를 방지해주는 템플릿 태그 문법
     default_if_none : 기본값을 설정하는 문법   -->
            <input type="text" class="form-control" id="subject" name="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
<!--위 코드에서 id, name 값이 같지만 둘 다 필요하다.  -->
        </div>
        <div>
            <label for="content">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>

    </form>
</div>

{% endblock %}

<!--
form : 입력된 데이터를 전송하기위한 태그.
1. 폼이 있는 페이지 접속.
2. 폼에 내용을 입력.
3. 저장(전송/ 속성 : submit)인 버튼을 눌렀을때 폼 안쪽의 모든 데이터를 서버(로컬서버:8000)로 전송.
4. django 에서는 받은 폼 데이터를 처리하기위해 form.py 로 넘겨줌.
    (서버는 받은 폼 데이터를 처리하기위해 웹프로그램으로 넘겨준다)
5. forms.py 에서 데이터를 받은 후 views.py 로 넘겨줌.
6. views.py 에서 데이터를 처리.
7. 처리결과에 따라 페이지를 로컬서버에 전송 .
8. 로컬서버는 받은 페이지를 브라우저에 전송.
9. 브라우저는 받은 페이지를 보여 줌.

폼 태그 속성
action : 폼을 전송할 서버 스크립트(템플릿)파일을 지정.
name   :  폼을 식별하기 위한 이름.
target : action 에서 지정한 스크립트 파일을 현재 창이 아니라 다른 위치에 열도록 지정하는 속성
method : 폼을 서버에 전송할 http 메서드를 정하는 방법(GET or POST)
          기본값은 GET
-->

templates/app1/question_form_bak0714.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border=bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장</button>

    </form>
</div>

{% endblock %}

templates/app1/question_list.html
{% extends 'base.html' %}
{% load filter %}
{% block content %}

<!-- templatetags 폴더를 app1에 만들기 그 폴더안에 filter.py 만들기-->
<div class="container my-3">
<!--
    페이징 : 컴퓨터가 데이터를 저장하고 검색하는 메모리 관리기법
    paginator.count : 전체 게시물 개수를 가져 옴.
    start_index : 현재 페이지의 시작 인덱스
    end_index : 현재 페이지의 끝 인덱스
    일련번호 = 전체 게시물 개수 - 시작 인덱스 - 현재 인덱스 +1
   -->
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}
            </td>
            <td class="text-left">
                <a href="{% url 'app1:detail' question.id %}">{{question.subject}}
                </a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger medium m-2">{{ question.answer_set.count }}</span>
                {% endif %}

            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다</td>
        </tr>
        {% endif %}

    </tbody>
    </table>
<!--    페이징 처리 view 영역   -->
<!--        부트스트랩 용 코드적용 (justify-content: center <-- css버전) -->
    <ul class="pagination justify-content-center">
<!--        has_previous : 이전 페이지가 있는지 유무를 확인-->
        {% if question_list.has_previous %}
        <li class="page-item">
<!--            previous_page_number : 이전 페이지 번호를 적는 것-->
            <a class="page-link" href="?page={{ question_list.privious_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page_item disabled">
            <a class="page_link" href="#" aria-disabled="true" tabindex="-1"></a>
        </li>
        {% endif %}
<!--        페이지 리스트 출력하기 -->
<!--        page_range : 페이지의 범위
            number : 현재 페이지 번호 -->
        {% for page_number in question_list.paginator.page_range %}
<!--        아래 줄에서 add:-2 를 add: -2 로 띄어쓰기 하면 에러발생 함.-->
        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
            {% if page_number == question_list.number %}

        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number}}">{{ page_number}}</a>
        </li>
        {% else %}
         <li class="page-item">
            <a class="page-link" href="?page={{ page_number}}">{{ page_number}}</a>
        </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!--        has_previous : 이전 페이지가 있는지 유무를 확인
                    has_next : 다음 페이지가 있는지 확인-->
        {% if question_list.has_next %}
        <li class="page-item">
        <!--        previous_page_number : 이전 페이지 번호를 적는 것
                    next_page_number : 다음 페이지 영역 -->
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page_item disabled">
            <a class="page_link" href="#" aria-disabled="true" tabindex="-1"></a>
        </li>
        {% endif %}
    </ul>



    <a href="{% url 'app1:question_create'%}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

templates/app1/question_list_backup0713.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
<link rel ="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'app1:detail' question.id %}">{{question.subject}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>게시글이 없습니다.</p>
{% endif %}

</body>
</html>