app1/urls.py
from django.urls import path

from . import views

# 'app1' => 아래 name='index'의 별칭
app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    # --- 상세보기 페이지 추가 21.07.12(king) detail, answer url 부여--------------------
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # --- 21.07.13 질문등록 url 부여 --------------------------------------------------
    path('question/create', views.question_create, name='question_create'),
    # --- 21.07.21. 퀴즈 : question_modify url 등록. 위에서 형식 참조. 규칙성 있게 만들면 추후 사용 편리성 증대 -------
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
]

common/urls.py
from django.urls import path

from . import views
# 윗 줄 views 와 아래의 views 는 다른 목적으로 작용. 아래쪽 views 는 LoginView 를 사용하기 위한 views 임.
from django.contrib.auth import views as auth_views

app_name = 'common'

# 세션 : 일정시간동안 같은 사용자로부터 들어오는 요청을 하나의 상태로 보고 그 상태를 일정하게
#       유지시키는 기술(사이트 방문자가 사이트에 접속해 있는 상태)
#       일정시간 : 사이트에 접속한 순간부터 브라우저 종료까지
# 세션 특징 :
# 1. 웹서버에 상태를 유지하기위한 정보를 저장.
# 2. 웹 서버에 저장되는 쿠키 = 세션 쿠키(검색 해 볼것!)
# 3.
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel ="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>ㅋㅋㅋㅋㅋㅋㅋ</title>
</head>
<body>
<!-- navbar 추가 21.07.16 King -->
{% include "navbar.html" %}

{% block content %}
{% endblock %}

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <!--필드오류 출력 / 필드오류 : 입력값 누락, 형식에 맞지않는값 입력오류 -->
            <div class="alert alert-danger" role="alert">
            <strong>{{ field.label }}</strong>
            {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
        {% for error in form.non_field_errors %}
            <!--넌필드오류 출력 : 넌필드오류 : 입력값과 관계없이 발생한 오류. -->
            <div class="alert alert-danger" role="alert">
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
{% endif %}

templates/navbar.html
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">-->
<!-- 아래의 navbar-extend-lg(lg 는 로그인 관련 코드로 추정/ 없애면 로그인 버튼이 사라짐) -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom">
    <a class="navbar-brand" href="{% url 'app1:index' %}">프로젝트</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
<!--                현재 로그인 한건지 아닌지 판단해주는 템플릿 -->
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}님(로그아웃)</a>
                {% else %}
                <div class="row my-3">
                    <div class="col-4">
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    </div>
                    <div class="col-8 text-right">
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    </div>
                </div>
    </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>